events {}

http {
  upstream backend_app {
    server app:8000;
  }

  upstream admin_frontend {
    server admin-frontend:80;
  }

  server {
    listen 80;

    # Статический админ-фронтенд
    location /database/ {
      proxy_pass http://admin_frontend/;
    }

    # API бэкенда для админки
    location /database/api/ {
      proxy_pass http://backend_app;
    }
  }
}

